"""empty message

Revision ID: 29b962a488c7
Revises: 93da6f8e306f
Create Date: 2019-09-01 11:18:42.450601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b962a488c7'
down_revision = '93da6f8e306f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_top'), 'post', ['top'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_top'), table_name='post')
    # ### end Alembic commands ###
