"""empty message

Revision ID: 93da6f8e306f
Revises: 7ac7c0038799
Create Date: 2019-09-01 10:41:40.539482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93da6f8e306f'
down_revision = '7ac7c0038799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('top', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'top')
    # ### end Alembic commands ###
