"""empty message

Revision ID: 97341949a384
Revises: 1ba39e2641d8
Create Date: 2019-09-15 08:50:37.124739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97341949a384'
down_revision = '1ba39e2641d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zans_timestamp'), 'zans', ['timestamp'], unique=False)
    op.create_index(op.f('ix_zans_type'), 'zans', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zans_type'), table_name='zans')
    op.drop_index(op.f('ix_zans_timestamp'), table_name='zans')
    op.drop_table('zans')
    # ### end Alembic commands ###
