"""empty message

Revision ID: a39876df3c70
Revises: 97341949a384
Create Date: 2019-09-15 08:57:35.644099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39876df3c70'
down_revision = '97341949a384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zans', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.add_column('zans', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'zans', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'zans', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zans', type_='foreignkey')
    op.drop_constraint(None, 'zans', type_='foreignkey')
    op.drop_column('zans', 'post_id')
    op.drop_column('zans', 'comment_id')
    # ### end Alembic commands ###
