"""empty message

Revision ID: b549d08f5bcd
Revises: a39876df3c70
Create Date: 2019-09-23 20:27:54.341644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b549d08f5bcd'
down_revision = 'a39876df3c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zans_timestamp'), 'zans', ['timestamp'], unique=False)
    op.create_index(op.f('ix_zans_type'), 'zans', ['type'], unique=False)
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.create_foreign_key(None, 'parent_child', 'comments', ['child_id'], ['id'])
    op.create_foreign_key(None, 'parent_child', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.create_foreign_key(None, 'parent_child', 'users', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'parent_child', 'users', ['child_id'], ['id'])
    op.drop_index(op.f('ix_zans_type'), table_name='zans')
    op.drop_index(op.f('ix_zans_timestamp'), table_name='zans')
    op.drop_table('zans')
    # ### end Alembic commands ###
