"""empty message

Revision ID: cf14f26d79ac
Revises: b549d08f5bcd
Create Date: 2019-09-29 15:42:33.284643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf14f26d79ac'
down_revision = 'b549d08f5bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.create_foreign_key(None, 'parent_child', 'comments', ['child_id'], ['id'])
    op.create_foreign_key(None, 'parent_child', 'comments', ['parent_id'], ['id'])
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login_ip')
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.create_foreign_key(None, 'parent_child', 'users', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'parent_child', 'users', ['child_id'], ['id'])
    # ### end Alembic commands ###
